version: "3.3"

services:
  matrix:
    image: "matrixdotorg/synapse"
    container_name: "matrix"
    ports:
      - "8088:8008"
    volumes:
      - "./synapse-data:/data"
    environment:
      SYNAPSE_SERVER_NAME: "homeserver.localhost"
      SYNAPSE_REPORT_STATS: "yes"
    depends_on:
      - "matrix_postgresql"
    # condition: service_healthy
    # command: generate

  matrix_postgresql:
    image: postgres:11-alpine
    container_name: "matrix_postgresql"
    restart: always
    # ports:
    #   - "5532:5432"
    environment:
      POSTGRES_PASSWORD: 1
      POSTGRES_USER: synapse
      POSTGRES_DB: synapse
      POSTGRES_INITDB_ARGS: "--encoding='UTF8' --lc-collate='C' --lc-ctype='C'"
    healthcheck:
      test: 'psql -U synapse -d synapse -c "SELECT 1 FROM pg_constraint WHERE conname = ''ui_auth_sessions_ips_session_id_fkey''"'
      # start_period: 1s
      interval: 5s
    volumes:
      - "synapse_postgresdata:/var/lib/postgresql/"

  storage:
    image: minio/minio
    container_name: storage
    ports:
      - 9010:9000
      - 9011:9001
    command: server /data --console-address ":9011"
volumes:
  synapse_postgresdata:
  miniodata:
